name: Build and Test MongoDB-CRUD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'

      - name: Build
        run: go build

  test:
    name: Test-Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'

      - name: Install dependencies
        run: 
          go mod tidy
          go mod verify

      - name: Run tests
        run: go test -v ./...
