name: Build and Test MongoDB-CRUD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'
          
      - name: Install Make
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Build
        run: make build

  test:
    name: Test-Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.4'

      - name: Install dependencies
        run: 
          go mod tidy

      - name: Run tests
        run: go test -v ./...
